### ISSUE TITLE
Can we disable mouse events (like hover and click) ? 

### ISSUE THREAD

**Issue by jgauna** [aral/gala-alt-tab-plus#15]
I was about to uninstall Elementary and come back to Ubuntu Mate but I found this, so thanks!

The "ugly" that I founded is that if I'm using the mouse and chaging from window to window, it gets the mouse action so catts redirects me to the wrong application in the manager.

Is there any way to disable the mouse events for preventing this behaviour?

**Comment by aral** [comment]
Hi @jgauna, 

Thanks for opening an issue and apologies for the slow reply. I’m about to archive Catts as it has now been included as part of elementary OS in Gala. Further development work will be ongoing there.

You can reach their issue tracker at https://github.com/elementary/gala/issues
